# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_gaps <- function(seq) {
    .Call('genoslideR_find_gaps', PACKAGE = 'genoslideR', seq)
}

