# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_gaps <- function(seq) {
    .Call('genoslideR_find_gaps', PACKAGE = 'genoslideR', seq)
}

make_ungapped_ranges <- function(start, end, gaprange) {
    .Call('genoslideR_make_ungapped_ranges', PACKAGE = 'genoslideR', start, end, gaprange)
}

make_gapped_ranges <- function(start, end, gapstart, gapwidth, aln_len) {
    .Call('genoslideR_make_gapped_ranges', PACKAGE = 'genoslideR', start, end, gapstart, gapwidth, aln_len)
}

